### ISSUE TITLE
[PE-D][Tester B] Unable to use the settle feature

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-T15-3/tp#120]
![image.png](https://raw.githubusercontent.com/Praneet-25/ped/main/files/3a15a3c9-e4f1-4da8-9b8f-8265207e5bfe.png)

I tried in all possible combinations. Payer owes payee, payee owes payer and they do not work and it displays invalid command.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Praneet-25/ped#2

**Comment by avrilgk** [comment]
Tester was not following the given syntax. Closing issue with no code update.
